# Generated by Django 4.2.15 on 2024-10-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_question_user_reply_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_body",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="reply",
            name="reply_body",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
