# Generated by Django 4.2.15 on 2024-10-15 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0006_alter_question_user_alter_reply_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                default=polls.models.get_deleted_user,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="user",
            field=models.ForeignKey(
                default=polls.models.get_deleted_user,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
