# Generated by Django 4.2.15 on 2025-01-13 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0007_alter_question_user_alter_reply_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="rating",
            field=models.ManyToManyField(
                blank=True, related_name="question_rating", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="rating",
            field=models.ManyToManyField(
                blank=True, related_name="reply_rating", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
