# Generated by Django 4.2.15 on 2025-01-16 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0008_question_rating_reply_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True,
                related_name="question_bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True, related_name="reply_bookmark", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
