# Generated by Django 4.2.15 on 2025-02-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_question_bookmark_reply_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
