name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: aagarwal32/Wisqer-django-website/.github/workflows/test-wisqer.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: django-wisqer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}

    - name: Login to DO container registry with short-lived creds
      run: doctl registry login --expiry-seconds 1200

    - name: Build container image
      working-directory: .
      run: |
        docker build -f Dockerfile --platform linux/amd64 \
          -t registry.digitalocean.com/django-wisqer-pcr/djangodocker:latest \
          -t registry.digitalocean.com/django-wisqer-pcr/djangodocker:${GITHUB_SHA::7} \
          .

    - name: Push image
      run: |
        docker push registry.digitalocean.com/django-wisqer-pcr/djangodocker --all-tags

    - name: Wisqer cluster kubeconfig file w/ short lived creds
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}

    - name: Update deployment secrets
      run: |
        cat << EOF >> ./.env.prod
        ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
        DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}

        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        EOF
        kubectl delete django-wisqer-web-prod-env
        kubectl create secret generic django-wisqer-web-prod-env --from-env-file=./.env.prod

    - name: Update deployment image
      run: |
        kubectl set image deployment/django-wisqer-web-deployment \
        djangodocker=registry.digitalocean.com/django-wisqer-pcr/djangodocker:${GITHUB_SHA::7}

    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/django-wisqer-web-deployment

    - name: Migrate database
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=django-wisqer-web-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
