name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: aagarwal32/Wisqer-django-website/.github/workflows/test-wisqer.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: temporary-test-key

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to DO container registry with short-lived creds
      run: doctl registry login --expiry-seconds 1200
    - name: Build container image
      working-directory: .
      run: |
        docker build -f Dockerfile --platform linux/amd64 \
          -t registry.digitalocean.com/django-wisqer-pcr/djangodocker:latest \
          -t registry.digitalocean.com/django-wisqer-pcr/djangodocker:${GITHUB_SHA::7} \
          .
    - name: Push image
      run: |
        docker push registry.digitalocean.com/django-wisqer-pcr/djangodocker --all-tags
